### ISSUE TITLE
No files in data and saved_models

### ISSUE THREAD

**Issue by usmanmukhtar** [CarstenIsert/DeepBurn#1]
Hi,
I want to work on your project as coincidentally it's very similar to my final year project. I wanted to create such an algorithm that can do 3 major things.
1) Classify the wound on face/body parts
2) Degree of burn(superficial or deep)
3) percentage of burn for critical treatment.

i want to use your code but you have mentioned that its not complete. I am new to AI/ML but after studying a lot i now know about CNN, RCNN, and also have implemented YOLO. But still need assistance. Maybe if you can help me out that will be a blessing. Hope you respond to me, Thank you!
Regards Usman Mukhtar
usmanmukhtar432@gmail.com

**Comment by CarstenIsert** [comment]
Hi Usman,

As I pointed out in the README, the major problem was getting access to real world data to make progress on this. I didn't succeed in getting this access. I think the only way around this would be to set up a project within a university with the burn unit and get them to share the data and also do the labelling. 
Unfortunately, I can't help much more as the main issues will come up once you experiment with the data and have to make adjustments.

Wish you all the best for your project.

Best,
Carsten

**Comment by usmanmukhtar** [comment]
Thank you so much for your response. what if i am able to get the images from the burn center, or what if, I had an idea that to apply makeup on our self, would that be effective/possible for your algorithm to work. In your Readme file you have said that you are using transfer learning... by that you mean that you only needed the data for your algorithm to work right?

Thank you!
Regards,
Usman
P.S: Sorry if these are irreverent questions, i am still on a learning curve

**Comment by CarstenIsert** [comment]
Hi Usman,

applying makeup is definitely not going to work. If you can’t get access to medical data, an image search on Google and Bing can help you to get a few images, but you need to be careful with the copyright of these images and you need to do the labelling / semantic segmentation yourself which you can easily get wrong.

As I said, the only way I see is to start an official cooperation with a burn center and doctors who can help you with the labelling.
When you have the data, a lot of work will go into the preparation of the data.

Fine tuning in this area means that you take an image net pre-trained network and replace the final layers for the classification and then retrain the network with the weights of the first layers fixed (or allowing slight changes) and the last layers learning the new classification.

Best,

Carsten

**Comment by usmanmukhtar** [comment]
Thank you.. now i am clear with everything for now.. i do have contacts in the burn center and i can get the labeling done by them.. hopefully this works out. And thank you so much for your help i really appriciate it. If get stuck in the future would you help me if i message you?
