### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tuvovan** [CarstenIsert/DeepBurn#2]
Hi,
Thank you for your great work,

Could you please tell me where I can find the dataset? I went to the medetec website but there is no specific dataset such as first level, second level of burn like you used in the jupyter notebook.

Thank you!

**Comment by CarstenIsert** [comment]
Hi Vo,

Unfortunately, I didn’t succeed in getting access to the data and had to stop working on this project.
As this has been quite some time ago, I have no idea on further progress in this area, but would be interested if you found some more research or data.

Best,

Carsten

**Comment by tuvovan** [comment]
yeah thanks!
